# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facerig.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_faceUI_Form(object):
    def setupUi(self, faceUI_Form):
        faceUI_Form.setObjectName(_fromUtf8("faceUI_Form"))
        faceUI_Form.resize(472, 618)
        faceUI_Form.setStyleSheet(_fromUtf8("background-color: rgb(71, 71, 71);"))
        self.gridLayout = QtGui.QGridLayout(faceUI_Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(faceUI_Form)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);\n"
"color: rgb(255, 255, 255);"))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rebulidAllBone_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.rebulidAllBone_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.rebulidAllBone_pushButton.setObjectName(_fromUtf8("rebulidAllBone_pushButton"))
        self.gridLayout_5.addWidget(self.rebulidAllBone_pushButton, 2, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 385, 221))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBox.setAcceptDrops(True)
        self.toolBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet(_fromUtf8("background-color: rgb(179, 183, 202);\n"
""))
        self.toolBox.setFrameShape(QtGui.QFrame.Panel)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.checkBox_9 = QtGui.QCheckBox(self.page_4)
        self.checkBox_9.setText(_fromUtf8(""))
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.verticalLayout_7.addWidget(self.checkBox_9)
        self.importForeHeadBone_pushButton_15 = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_15.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_15.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_15.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_15.setObjectName(_fromUtf8("importForeHeadBone_pushButton_15"))
        self.verticalLayout_7.addWidget(self.importForeHeadBone_pushButton_15)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.page_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.layoutWidget_2)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.importForeHeadBone_pushButton_9 = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_9.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_9.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_9.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_9.setObjectName(_fromUtf8("importForeHeadBone_pushButton_9"))
        self.verticalLayout_2.addWidget(self.importForeHeadBone_pushButton_9)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.splitter_3 = QtGui.QSplitter(self.page_6)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkBox_5 = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.importForeHeadBone_pushButton_11 = QtGui.QPushButton(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_11.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_11.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_11.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_11.setObjectName(_fromUtf8("importForeHeadBone_pushButton_11"))
        self.verticalLayout_3.addWidget(self.importForeHeadBone_pushButton_11)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.splitter_4 = QtGui.QSplitter(self.page_7)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.layoutWidget_3 = QtGui.QWidget(self.splitter_4)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_4 = QtGui.QCheckBox(self.layoutWidget_3)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.verticalLayout_4.addWidget(self.checkBox_4)
        self.importForeHeadBone_pushButton_10 = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_10.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_10.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_10.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_10.setObjectName(_fromUtf8("importForeHeadBone_pushButton_10"))
        self.verticalLayout_4.addWidget(self.importForeHeadBone_pushButton_10)
        self.gridLayout_9.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.splitter_5 = QtGui.QSplitter(self.page_8)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.layoutWidget_5 = QtGui.QWidget(self.splitter_5)
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.verticalLayout_5.addWidget(self.checkBox_6)
        self.importForeHeadBone_pushButton_12 = QtGui.QPushButton(self.layoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_12.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_12.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_12.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_12.setObjectName(_fromUtf8("importForeHeadBone_pushButton_12"))
        self.verticalLayout_5.addWidget(self.importForeHeadBone_pushButton_12)
        self.gridLayout_10.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 365, 69))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.gridLayout_11 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.splitter_6 = QtGui.QSplitter(self.page_9)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.layoutWidget_6 = QtGui.QWidget(self.splitter_6)
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox_7 = QtGui.QCheckBox(self.layoutWidget_6)
        self.checkBox_7.setText(_fromUtf8(""))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.verticalLayout_6.addWidget(self.checkBox_7)
        self.importForeHeadBone_pushButton_13 = QtGui.QPushButton(self.layoutWidget_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importForeHeadBone_pushButton_13.sizePolicy().hasHeightForWidth())
        self.importForeHeadBone_pushButton_13.setSizePolicy(sizePolicy)
        self.importForeHeadBone_pushButton_13.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton_13.setObjectName(_fromUtf8("importForeHeadBone_pushButton_13"))
        self.verticalLayout_6.addWidget(self.importForeHeadBone_pushButton_13)
        self.gridLayout_11.addWidget(self.splitter_6, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_9, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.toolBox, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_18.addWidget(self.scrollArea, 5, 0, 1, 1)
        self.headmeshlist_listWidget = QtGui.QListWidget(self.groupBox_2)
        self.headmeshlist_listWidget.setStyleSheet(_fromUtf8("background-color: rgb(37, 118, 147);"))
        self.headmeshlist_listWidget.setObjectName(_fromUtf8("headmeshlist_listWidget"))
        self.gridLayout_18.addWidget(self.headmeshlist_listWidget, 1, 0, 1, 1)
        self.setheadmesh_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.setheadmesh_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.setheadmesh_pushButton.setObjectName(_fromUtf8("setheadmesh_pushButton"))
        self.gridLayout_18.addWidget(self.setheadmesh_pushButton, 3, 0, 1, 1)
        self.splitter_7 = QtGui.QSplitter(self.groupBox_2)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.currentfacemesh_label = QtGui.QLabel(self.splitter_7)
        self.currentfacemesh_label.setObjectName(_fromUtf8("currentfacemesh_label"))
        self.face_mesh_lineEdit = QtGui.QLineEdit(self.splitter_7)
        self.face_mesh_lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(37, 118, 147);"))
        self.face_mesh_lineEdit.setObjectName(_fromUtf8("face_mesh_lineEdit"))
        self.gridLayout_18.addWidget(self.splitter_7, 2, 0, 1, 1)
        self.loadmeshList__pushButton = QtGui.QPushButton(self.groupBox_2)
        self.loadmeshList__pushButton.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.loadmeshList__pushButton.setObjectName(_fromUtf8("loadmeshList__pushButton"))
        self.gridLayout_18.addWidget(self.loadmeshList__pushButton, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.snapForeHeadMeshToHeadMesh_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.snapForeHeadMeshToHeadMesh_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.snapForeHeadMeshToHeadMesh_pushButton.setObjectName(_fromUtf8("snapForeHeadMeshToHeadMesh_pushButton"))
        self.gridLayout_5.addWidget(self.snapForeHeadMeshToHeadMesh_pushButton, 3, 0, 1, 1)
        self.setforeheadbone_pushButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setforeheadbone_pushButton.sizePolicy().hasHeightForWidth())
        self.setforeheadbone_pushButton.setSizePolicy(sizePolicy)
        self.setforeheadbone_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.setforeheadbone_pushButton.setObjectName(_fromUtf8("setforeheadbone_pushButton"))
        self.gridLayout_5.addWidget(self.setforeheadbone_pushButton, 1, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.bneMir_pushButton = QtGui.QPushButton(self.splitter)
        self.bneMir_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.bneMir_pushButton.setObjectName(_fromUtf8("bneMir_pushButton"))
        self.bneMir_pushButton_2 = QtGui.QPushButton(self.splitter)
        self.bneMir_pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(138, 141, 156);"))
        self.bneMir_pushButton_2.setObjectName(_fromUtf8("bneMir_pushButton_2"))
        self.gridLayout_5.addWidget(self.splitter, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tabWidgetPage1)
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(144, 127, 127);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tabWidgetPage2)
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setStyleSheet(_fromUtf8("background-color: rgb(118, 119, 129);"))
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.toolBox_2 = QtGui.QToolBox(self.tab)
        self.toolBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBox_2.setStyleSheet(_fromUtf8("background-color: rgb(103, 103, 103);"))
        self.toolBox_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox_2.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox_2.setObjectName(_fromUtf8("toolBox_2"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 385, 124))
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_12 = QtGui.QGridLayout(self.page)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_8.addWidget(self.pushButton)
        self.widget = QtGui.QWidget(self.page)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widget)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_13.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget)
        self.pushButton_3 = QtGui.QPushButton(self.page)
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.gridLayout_12.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 385, 124))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_14 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.pushButton_5 = QtGui.QPushButton(self.page_2)
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_15.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.page_2)
        self.pushButton_6.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_15.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.page_2)
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_15.addWidget(self.pushButton_7, 1, 0, 1, 2)
        self.gridLayout_14.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.toolBox_2.addItem(self.page_2, _fromUtf8(""))
        self.gridLayout_16.addWidget(self.toolBox_2, 0, 0, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 383, 170))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_16.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.scrollArea_3 = QtGui.QScrollArea(self.tab)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 383, 170))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_16.addWidget(self.scrollArea_3, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.tab_2)
        self.widget_2.setStyleSheet(_fromUtf8("background-color: rgb(38, 122, 152);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_17 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setStyleSheet(_fromUtf8("background-color: rgb(38, 122, 152);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_17.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_2)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_4 = QtGui.QWidget(self.tab_2)
        self.widget_4.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_20 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_5 = QtGui.QLabel(self.widget_4)
        self.label_5.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_20.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(self.tab_2)
        self.widget_5.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_21 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_6 = QtGui.QLabel(self.widget_5)
        self.label_6.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_21.addWidget(self.label_6, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.widget_8 = QtGui.QWidget(self.tab_2)
        self.widget_8.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_25 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.checkBox = QtGui.QCheckBox(self.widget_8)
        self.checkBox.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_25.addWidget(self.checkBox, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.widget_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget_3 = QtGui.QWidget(self.tab_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_19 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_3 = QtGui.QLabel(self.widget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_19.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton_8 = QtGui.QPushButton(self.tab_2)
        self.pushButton_8.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.tab_2)
        self.pushButton_9.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setChecked(True)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.tab_2)
        self.pushButton_10.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        self.pushButton_11.setAcceptDrops(False)
        self.pushButton_11.setAutoFillBackground(False)
        self.pushButton_11.setStyleSheet(_fromUtf8("selection-background-color: rgb(138, 141, 156);\n"
"background-color: rgb(0, 170, 255);"))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setChecked(True)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.pushButton_12 = QtGui.QPushButton(self.tab_2)
        self.pushButton_12.setAcceptDrops(False)
        self.pushButton_12.setAutoFillBackground(False)
        self.pushButton_12.setStyleSheet(_fromUtf8("alternate-background-color: rgb(0, 170, 255);\n"
"background-color: rgb(0, 170, 255);\n"
""))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setChecked(True)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.widget_6 = QtGui.QWidget(self.tab_2)
        self.widget_6.setStyleSheet(_fromUtf8("background-color: rgb(103, 103, 103);"))
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.gridLayout_22 = QtGui.QGridLayout(self.widget_6)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_4 = QtGui.QLabel(self.widget_6)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_22.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.verticalLayout_10.addWidget(self.listWidget_2)
        self.pushButton_13 = QtGui.QPushButton(self.tab_2)
        self.pushButton_13.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayout_10.addWidget(self.pushButton_13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.widget_7 = QtGui.QWidget(self.tab_2)
        self.widget_7.setStyleSheet(_fromUtf8("background-color: rgb(103, 103, 103);"))
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.gridLayout_24 = QtGui.QGridLayout(self.widget_7)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.label_7 = QtGui.QLabel(self.widget_7)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_24.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.widget_7)
        self.listWidget_3 = QtGui.QListWidget(self.tab_2)
        self.listWidget_3.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.verticalLayout_11.addWidget(self.listWidget_3)
        self.pushButton_14 = QtGui.QPushButton(self.tab_2)
        self.pushButton_14.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.verticalLayout_11.addWidget(self.pushButton_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_15 = QtGui.QPushButton(self.tab_2)
        self.pushButton_15.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(96, 98, 109);"))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.horizontalLayout_8.addWidget(self.pushButton_15)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_8.addWidget(self.doubleSpinBox)
        self.pushButton_16 = QtGui.QPushButton(self.tab_2)
        self.pushButton_16.setStyleSheet(_fromUtf8("background-color: rgb(96, 98, 109);"))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.horizontalLayout_8.addWidget(self.pushButton_16)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_17 = QtGui.QPushButton(self.tab_2)
        self.pushButton_17.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.horizontalLayout_7.addWidget(self.pushButton_17)
        self.pushButton_18 = QtGui.QPushButton(self.tab_2)
        self.pushButton_18.setStyleSheet(_fromUtf8("background-color: rgb(55, 56, 62);"))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.horizontalLayout_7.addWidget(self.pushButton_18)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.pushButton_19 = QtGui.QPushButton(self.tab_2)
        self.pushButton_19.setStyleSheet(_fromUtf8("background-color: rgb(75, 78, 99);"))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.verticalLayout_9.addWidget(self.pushButton_19)
        self.gridLayout_23.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName(_fromUtf8("tabWidgetPage3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabWidgetPage3)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 30, 301, 371))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tabWidget.addTab(self.tabWidgetPage3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtGui.QFrame(faceUI_Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(faceUI_Form)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(2)
        self.toolBox.layout().setSpacing(2)
        self.tabWidget_2.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(0)
        self.toolBox_2.layout().setSpacing(4)
        QtCore.QMetaObject.connectSlotsByName(faceUI_Form)

    def retranslateUi(self, faceUI_Form):
        faceUI_Form.setWindowTitle(_translate("faceUI_Form", "faceUI_Win", None))
        self.groupBox_2.setTitle(_translate("faceUI_Form", "Jnt_Import", None))
        self.rebulidAllBone_pushButton.setText(_translate("faceUI_Form", "重置所有骨骼", None))
        self.importForeHeadBone_pushButton_15.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("faceUI_Form", "ForeHead_Create", None))
        self.importForeHeadBone_pushButton_9.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("faceUI_Form", "Brow_Create", None))
        self.importForeHeadBone_pushButton_11.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("faceUI_Form", "Eye_Create", None))
        self.importForeHeadBone_pushButton_10.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("faceUI_Form", "Check_Create", None))
        self.importForeHeadBone_pushButton_12.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("faceUI_Form", "Nose_Create", None))
        self.importForeHeadBone_pushButton_13.setText(_translate("faceUI_Form", "导入基础骨骼", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("faceUI_Form", "Mouth_Create", None))
        self.setheadmesh_pushButton.setText(_translate("faceUI_Form", "设置面部模型", None))
        self.currentfacemesh_label.setText(_translate("faceUI_Form", "当前面部模型：", None))
        self.loadmeshList__pushButton.setText(_translate("faceUI_Form", "载入模型列表", None))
        self.snapForeHeadMeshToHeadMesh_pushButton.setText(_translate("faceUI_Form", "(选择)吸附模型", None))
        self.setforeheadbone_pushButton.setText(_translate("faceUI_Form", "生成基础骨骼", None))
        self.bneMir_pushButton.setText(_translate("faceUI_Form", "L>TO>R镜像", None))
        self.bneMir_pushButton_2.setText(_translate("faceUI_Form", "R>TO>L镜像", None))
        self.pushButton_4.setText(_translate("faceUI_Form", "绑定Rigging", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("faceUI_Form", "导入骨骼", None))
        self.pushButton.setText(_translate("faceUI_Form", "生成缩放", None))
        self.label.setText(_translate("faceUI_Form", "CurrentScaleType", None))
        self.pushButton_3.setText(_translate("faceUI_Form", "拷贝权重到晶格", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page), _translate("faceUI_Form", "添加头部缩放", None))
        self.pushButton_5.setText(_translate("faceUI_Form", "创建定位点", None))
        self.pushButton_6.setText(_translate("faceUI_Form", "吸附定位点", None))
        self.pushButton_7.setText(_translate("faceUI_Form", "生成次级", None))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_2), _translate("faceUI_Form", "创建面部次级", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("faceUI_Form", "设置升级", None))
        self.label_2.setText(_translate("faceUI_Form", "CurrentSetModel:SDK", None))
        self.pushButton_2.setText(_translate("faceUI_Form", "驱动（驱动修行切换）", None))
        self.label_5.setText(_translate("faceUI_Form", "当前显示side:_L", None))
        self.label_6.setText(_translate("faceUI_Form", "*_L(点击切换)", None))
        self.checkBox.setText(_translate("faceUI_Form", "镜像", None))
        self.label_3.setText(_translate("faceUI_Form", "当前值：", None))
        self.lineEdit.setText(_translate("faceUI_Form", "100", None))
        self.pushButton_8.setText(_translate("faceUI_Form", "50%", None))
        self.pushButton_9.setText(_translate("faceUI_Form", "100%", None))
        self.pushButton_10.setText(_translate("faceUI_Form", "设置", None))
        self.pushButton_11.setText(_translate("faceUI_Form", "镜像修型", None))
        self.lineEdit_2.setText(_translate("faceUI_Form", "0.0100", None))
        self.pushButton_12.setText(_translate("faceUI_Form", "参考", None))
        self.label_4.setText(_translate("faceUI_Form", "表情属性", None))
        self.pushButton_13.setText(_translate("faceUI_Form", "添加新属性", None))
        self.label_7.setText(_translate("faceUI_Form", "控制/修型列表", None))
        self.pushButton_14.setText(_translate("faceUI_Form", "检查位移", None))
        self.pushButton_15.setText(_translate("faceUI_Form", "+", None))
        self.pushButton_16.setText(_translate("faceUI_Form", "-", None))
        self.pushButton_17.setText(_translate("faceUI_Form", "L<<R", None))
        self.pushButton_18.setText(_translate("faceUI_Form", "L>>R", None))
        self.pushButton_19.setText(_translate("faceUI_Form", "重新定义", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("faceUI_Form", "属性修正", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("faceUI_Form", "设置表情", None))
        self.groupBox_3.setTitle(_translate("faceUI_Form", "BlendShape", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("faceUI_Form", "修形", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    faceUI_Form = QtGui.QWidget()
    ui = Ui_faceUI_Form()
    ui.setupUi(faceUI_Form)
    faceUI_Form.show()
    sys.exit(app.exec_())

