# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FaceWin_Form(object):
    def setupUi(self, FaceWin_Form):
        FaceWin_Form.setObjectName(_fromUtf8("FaceWin_Form"))
        FaceWin_Form.resize(800, 800)
        FaceWin_Form.setMinimumSize(QtCore.QSize(800, 0))
        FaceWin_Form.setMaximumSize(QtCore.QSize(800, 800))
        self.gridLayout = QtGui.QGridLayout(FaceWin_Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.faceRigBase_tabWidget = QtGui.QTabWidget(FaceWin_Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.faceRigBase_tabWidget.setFont(font)
        self.faceRigBase_tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(99, 99, 99);"))
        self.faceRigBase_tabWidget.setMovable(True)
        self.faceRigBase_tabWidget.setObjectName(_fromUtf8("faceRigBase_tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 739, 1239))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setMaximumSize(QtCore.QSize(1444, 235))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.widget_8 = QtGui.QWidget(self.groupBox_6)
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_8.setStyleSheet(_fromUtf8("background-color: rgb(162, 223, 255);"))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.gridLayout_20 = QtGui.QGridLayout(self.widget_8)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.checkBox_24 = QtGui.QCheckBox(self.widget_8)
        self.checkBox_24.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.horizontalLayout_15.addWidget(self.checkBox_24)
        self.label_4 = QtGui.QLabel(self.widget_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_15.addWidget(self.label_4)
        self.gridLayout_20.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.widget_8)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.checkBox_27 = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_27.setChecked(True)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.horizontalLayout_17.addWidget(self.checkBox_27, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.checkBox_29 = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_29.setChecked(True)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.horizontalLayout_17.addWidget(self.checkBox_29, QtCore.Qt.AlignHCenter)
        self.checkBox_30 = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_30.setChecked(True)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.horizontalLayout_17.addWidget(self.checkBox_30)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_17)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.gridLayout_19.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_6, 4, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setMaximumSize(QtCore.QSize(1444, 235))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.widget_4 = QtGui.QWidget(self.groupBox_5)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_4.setStyleSheet(_fromUtf8("background-color: rgb(162, 223, 255);"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.checkBox_18 = QtGui.QCheckBox(self.widget_4)
        self.checkBox_18.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.horizontalLayout_11.addWidget(self.checkBox_18)
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_11.addWidget(self.label_3)
        self.gridLayout_18.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.horizontalLayout_13.addWidget(self.checkBox_14, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_5.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.verticalLayout_6.addWidget(self.spinBox_5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_6)
        self.checkBox_19 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.horizontalLayout_13.addWidget(self.checkBox_19, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.spinBox_8 = QtGui.QSpinBox(self.groupBox_5)
        self.spinBox_8.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.verticalLayout_12.addWidget(self.spinBox_8, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.checkBox_21 = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.horizontalLayout_13.addWidget(self.checkBox_21, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_8.setMinimumSize(QtCore.QSize(75, 30))
        self.pushButton_8.setMaximumSize(QtCore.QSize(75, 30))
        self.pushButton_8.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_12.addWidget(self.pushButton_8)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.gridLayout_17.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_21.addWidget(self.checkBox_2, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.spinBox = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_21.addWidget(self.spinBox, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_21.addWidget(self.checkBox_3, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_21.addWidget(self.checkBox_4, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_5 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_21.addWidget(self.checkBox_5, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_2.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_21.addWidget(self.spinBox_2, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.spinBox_13 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_13.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_21.addWidget(self.spinBox_13, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.spinBox_14 = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_14.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_21.addWidget(self.spinBox_14, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox_31 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_31.setChecked(True)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.gridLayout_21.addWidget(self.checkBox_31, 1, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(19)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(75, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(75, 30))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_8.addWidget(self.pushButton_5, 8, 8, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 5, 7, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_25.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_25.setMaximumSize(QtCore.QSize(180, 30))
        self.checkBox_25.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);"))
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout_8.addWidget(self.checkBox_25, 5, 6, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_20.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_20.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_8.addWidget(self.checkBox_20, 1, 4, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_28.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_28.setMaximumSize(QtCore.QSize(100, 30))
        self.checkBox_28.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);"))
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.gridLayout_8.addWidget(self.checkBox_28, 2, 4, 1, 1)
        self.checkBox_22 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_22.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_22.setMaximumSize(QtCore.QSize(100, 30))
        self.checkBox_22.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);"))
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout_8.addWidget(self.checkBox_22, 7, 4, 1, 1)
        self.checkBox_39 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_39.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_39.setMaximumSize(QtCore.QSize(100, 50))
        self.checkBox_39.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 0);"))
        self.checkBox_39.setChecked(True)
        self.checkBox_39.setObjectName(_fromUtf8("checkBox_39"))
        self.gridLayout_8.addWidget(self.checkBox_39, 8, 4, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_26.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_26.setMaximumSize(QtCore.QSize(180, 30))
        self.checkBox_26.setStyleSheet(_fromUtf8("background-color: rgb(0, 85, 255);"))
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridLayout_8.addWidget(self.checkBox_26, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 5, 0, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridLayout_8.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_23.sizePolicy().hasHeightForWidth())
        self.checkBox_23.setSizePolicy(sizePolicy)
        self.checkBox_23.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_23.setMaximumSize(QtCore.QSize(100, 30))
        self.checkBox_23.setStyleSheet(_fromUtf8("background-color: rgb(87, 177, 255);"))
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout_8.addWidget(self.checkBox_23, 5, 4, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_11.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_11.setMaximumSize(QtCore.QSize(50, 40))
        self.spinBox_11.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_8.addWidget(self.spinBox_11, 6, 5, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_10.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_10.setMaximumSize(QtCore.QSize(50, 40))
        self.spinBox_10.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_8.addWidget(self.spinBox_10, 3, 5, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_9.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_9.setMaximumSize(QtCore.QSize(50, 40))
        self.spinBox_9.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_8.addWidget(self.spinBox_9, 3, 3, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_12.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_12.setMaximumSize(QtCore.QSize(50, 40))
        self.spinBox_12.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_8.addWidget(self.spinBox_12, 6, 3, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setMaximumSize(QtCore.QSize(1444, 235))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setStyleSheet(_fromUtf8("background-color: rgb(162, 223, 255);"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.widget)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_15 = QtGui.QCheckBox(self.widget)
        self.checkBox_15.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setAutoFillBackground(True)
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.horizontalLayout.addWidget(self.checkBox_15)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 6)
        self.checkBox_8 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_8.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout_2.addWidget(self.checkBox_8, 1, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_3.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_3.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout_2.addWidget(self.spinBox_3, 1, 1, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_6.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout_2.addWidget(self.checkBox_6, 1, 2, 1, 1)
        self.spinBox_6 = QtGui.QSpinBox(self.groupBox)
        self.spinBox_6.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_6.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_2.addWidget(self.spinBox_6, 1, 3, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_7.setMinimumSize(QtCore.QSize(50, 0))
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout_2.addWidget(self.checkBox_7, 1, 4, 1, 1)
        self._addForeHead_pushButton = QtGui.QPushButton(self.groupBox)
        self._addForeHead_pushButton.setMinimumSize(QtCore.QSize(75, 30))
        self._addForeHead_pushButton.setMaximumSize(QtCore.QSize(75, 30))
        self._addForeHead_pushButton.setSizeIncrement(QtCore.QSize(300, 0))
        self._addForeHead_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self._addForeHead_pushButton.setObjectName(_fromUtf8("_addForeHead_pushButton"))
        self.gridLayout_2.addWidget(self._addForeHead_pushButton, 1, 5, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.bow_groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.bow_groupBox.setMaximumSize(QtCore.QSize(1720, 235))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bow_groupBox.setFont(font)
        self.bow_groupBox.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.bow_groupBox.setObjectName(_fromUtf8("bow_groupBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.bow_groupBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.checkBox_13 = QtGui.QCheckBox(self.bow_groupBox)
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout_11.addWidget(self.checkBox_13, 1, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.bow_groupBox)
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout_11.addWidget(self.checkBox_9, 1, 1, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.bow_groupBox)
        self.spinBox_4.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_4.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_11.addWidget(self.spinBox_4, 1, 2, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.bow_groupBox)
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout_11.addWidget(self.checkBox_10, 1, 3, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.bow_groupBox)
        self.spinBox_7.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBox_7.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_11.addWidget(self.spinBox_7, 1, 4, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.bow_groupBox)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout_11.addWidget(self.checkBox_11, 1, 5, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.bow_groupBox)
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout_11.addWidget(self.checkBox_12, 1, 6, 1, 1)
        self._addBrow_pushButton = QtGui.QPushButton(self.bow_groupBox)
        self._addBrow_pushButton.setMinimumSize(QtCore.QSize(75, 30))
        self._addBrow_pushButton.setMaximumSize(QtCore.QSize(75, 30))
        self._addBrow_pushButton.setSizeIncrement(QtCore.QSize(300, 0))
        self._addBrow_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self._addBrow_pushButton.setObjectName(_fromUtf8("_addBrow_pushButton"))
        self.gridLayout_11.addWidget(self._addBrow_pushButton, 1, 7, 1, 1)
        self.widget_3 = QtGui.QWidget(self.bow_groupBox)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_3.setStyleSheet(_fromUtf8("background-color: rgb(162, 223, 255);"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.gridLayout_24 = QtGui.QGridLayout()
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.checkBox_17 = QtGui.QCheckBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridLayout_24.addWidget(self.checkBox_17, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_24.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_24, 0, 1, 1, 1)
        self.gridLayout_11.addWidget(self.widget_3, 0, 0, 1, 8)
        self.gridLayout_10.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.bow_groupBox, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color: rgb(162, 162, 162);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self._resetValue_pushButton = QtGui.QPushButton(self.groupBox_4)
        self._resetValue_pushButton.setMaximumSize(QtCore.QSize(300, 80))
        self._resetValue_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);"))
        self._resetValue_pushButton.setObjectName(_fromUtf8("_resetValue_pushButton"))
        self.gridLayout_14.addWidget(self._resetValue_pushButton, 1, 0, 1, 1)
        self._importBaseJnt_pushButton = QtGui.QPushButton(self.groupBox_4)
        self._importBaseJnt_pushButton.setMaximumSize(QtCore.QSize(300, 80))
        self._importBaseJnt_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self._importBaseJnt_pushButton.setObjectName(_fromUtf8("_importBaseJnt_pushButton"))
        self.gridLayout_14.addWidget(self._importBaseJnt_pushButton, 1, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_6.setMaximumSize(QtCore.QSize(300, 80))
        self.pushButton_6.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_14.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setMaximumSize(QtCore.QSize(300, 80))
        self.pushButton_10.setStyleSheet(_fromUtf8("background-color: rgb(210, 255, 167);"))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_14.addWidget(self.pushButton_10, 1, 3, 1, 1)
        self.backupBone_groupBox = QtGui.QGroupBox(self.groupBox_4)
        self.backupBone_groupBox.setObjectName(_fromUtf8("backupBone_groupBox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.backupBone_groupBox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.listWidget_2 = QtGui.QListWidget(self.backupBone_groupBox)
        self.listWidget_2.setStyleSheet(_fromUtf8("background-color: rgb(225, 240, 255);"))
        self.listWidget_2.setDragDropOverwriteMode(False)
        self.listWidget_2.setAlternatingRowColors(True)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_16.addWidget(self.listWidget_2, 0, 0, 3, 1)
        self.pushButton_7 = QtGui.QPushButton(self.backupBone_groupBox)
        self.pushButton_7.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_7.setMaximumSize(QtCore.QSize(120, 30))
        self.pushButton_7.setStyleSheet(_fromUtf8("background-color: rgb(114, 103, 96);"))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_16.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.backupBone_groupBox)
        self.pushButton_9.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(120, 30))
        self.pushButton_9.setStyleSheet(_fromUtf8("background-color: rgb(114, 103, 96);"))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_16.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.backupBone_groupBox)
        self.pushButton_14.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_14.setMaximumSize(QtCore.QSize(120, 30))
        self.pushButton_14.setStyleSheet(_fromUtf8("background-color: rgb(255, 125, 155);"))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_16.addWidget(self.pushButton_14, 2, 1, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.backupBone_groupBox, 2, 0, 1, 4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self._setPath_pushButton = QtGui.QPushButton(self.groupBox_4)
        self._setPath_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self._setPath_pushButton.setMaximumSize(QtCore.QSize(120, 30))
        self._setPath_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 127);"))
        self._setPath_pushButton.setObjectName(_fromUtf8("_setPath_pushButton"))
        self.horizontalLayout_2.addWidget(self._setPath_pushButton)
        self.gridLayout_14.addLayout(self.horizontalLayout_2, 3, 0, 1, 4)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color: rgb(84, 84, 84);"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_14.addWidget(self.pushButton_4, 0, 0, 1, 4)
        self.gridLayout_7.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.faceRigBase_tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.pushButton_12 = QtGui.QPushButton(self.tab_2)
        self.pushButton_12.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_22.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.tab_2)
        self.pushButton_11.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 255);"))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_22.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_22.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_22.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_22)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton_13 = QtGui.QPushButton(self.tab_2)
        self.pushButton_13.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.verticalLayout.addWidget(self.pushButton_13)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_23.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.faceRigBase_tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.faceRigBase_tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.faceRigBase_tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.faceRigBase_tabWidget, 0, 1, 1, 1)

        self.retranslateUi(FaceWin_Form)
        self.faceRigBase_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FaceWin_Form)

    def retranslateUi(self, FaceWin_Form):
        FaceWin_Form.setWindowTitle(_translate("FaceWin_Form", "FaceRig", None))
        self.groupBox_6.setTitle(_translate("FaceWin_Form", "Nose_Create", None))
        self.checkBox_24.setText(_translate("FaceWin_Form", "IO", None))
        self.label_4.setText(_translate("FaceWin_Form", "NoseCreate", None))
        self.checkBox_27.setText(_translate("FaceWin_Form", "Mid_Nose", None))
        self.checkBox_29.setText(_translate("FaceWin_Form", "OutNose", None))
        self.checkBox_30.setText(_translate("FaceWin_Form", "NoseFold", None))
        self.groupBox_5.setTitle(_translate("FaceWin_Form", "Check_Create", None))
        self.checkBox_18.setText(_translate("FaceWin_Form", "IO", None))
        self.label_3.setText(_translate("FaceWin_Form", "CheckCreate", None))
        self.checkBox_14.setText(_translate("FaceWin_Form", "In_Check", None))
        self.checkBox_19.setText(_translate("FaceWin_Form", "Mid_Check", None))
        self.checkBox_21.setText(_translate("FaceWin_Form", "Out_Check", None))
        self.pushButton_8.setText(_translate("FaceWin_Form", "AddExtra", None))
        self.groupBox_3.setTitle(_translate("FaceWin_Form", "Mouth_Create", None))
        self.checkBox_2.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_3.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_4.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_5.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_31.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.groupBox_2.setTitle(_translate("FaceWin_Form", "Eye_Create", None))
        self.pushButton_5.setText(_translate("FaceWin_Form", "AddExtra", None))
        self.checkBox_25.setText(_translate("FaceWin_Form", "outEyeLip", None))
        self.checkBox_20.setText(_translate("FaceWin_Form", "UpEyeSag", None))
        self.checkBox_28.setText(_translate("FaceWin_Form", "upEyeLip", None))
        self.checkBox_22.setText(_translate("FaceWin_Form", "dnEyeLip", None))
        self.checkBox_39.setText(_translate("FaceWin_Form", "DnEyeSag", None))
        self.checkBox_26.setText(_translate("FaceWin_Form", "inEyeLip", None))
        self.checkBox_16.setText(_translate("FaceWin_Form", "IO", None))
        self.checkBox_23.setText(_translate("FaceWin_Form", "Eye", None))
        self.groupBox.setTitle(_translate("FaceWin_Form", "ForeHead_Create", None))
        self.checkBox_15.setText(_translate("FaceWin_Form", "IO", None))
        self.label.setText(_translate("FaceWin_Form", "HeadFore", None))
        self.checkBox_8.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_6.setText(_translate("FaceWin_Form", "CheckBox", None))
        self.checkBox_7.setText(_translate("FaceWin_Form", "CheckBox", None))
        self._addForeHead_pushButton.setText(_translate("FaceWin_Form", "AddExtra", None))
        self.bow_groupBox.setTitle(_translate("FaceWin_Form", "Brow_Create", None))
        self.checkBox_13.setText(_translate("FaceWin_Form", "MidBrow", None))
        self.checkBox_9.setText(_translate("FaceWin_Form", "InBrow_Side", None))
        self.checkBox_10.setText(_translate("FaceWin_Form", "Brow_Mid", None))
        self.checkBox_11.setText(_translate("FaceWin_Form", "OutBrow_Side", None))
        self.checkBox_12.setText(_translate("FaceWin_Form", "Temple", None))
        self._addBrow_pushButton.setText(_translate("FaceWin_Form", "AddExtra", None))
        self.checkBox_17.setText(_translate("FaceWin_Form", "IO", None))
        self.label_2.setText(_translate("FaceWin_Form", "Brow", None))
        self.groupBox_4.setTitle(_translate("FaceWin_Form", "Jnt_Import", None))
        self._resetValue_pushButton.setText(_translate("FaceWin_Form", "Reset_Value", None))
        self._importBaseJnt_pushButton.setText(_translate("FaceWin_Form", "BulidBaseJnts", None))
        self.pushButton_6.setText(_translate("FaceWin_Form", "Left>>Right", None))
        self.pushButton_10.setText(_translate("FaceWin_Form", "Right>>Left", None))
        self.backupBone_groupBox.setTitle(_translate("FaceWin_Form", "bakeupBoneList", None))
        self.pushButton_7.setText(_translate("FaceWin_Form", "Load_Selected", None))
        self.pushButton_9.setText(_translate("FaceWin_Form", "RemoveSelected", None))
        self.pushButton_14.setText(_translate("FaceWin_Form", "ClearList", None))
        self._setPath_pushButton.setText(_translate("FaceWin_Form", "setPath", None))
        self.pushButton_4.setText(_translate("FaceWin_Form", "ImportBaseJntSize", None))
        self.faceRigBase_tabWidget.setTabText(self.faceRigBase_tabWidget.indexOf(self.tab), _translate("FaceWin_Form", "Jnt_Create", None))
        self.pushButton_12.setText(_translate("FaceWin_Form", "Load_HeadGrp", None))
        self.pushButton_11.setText(_translate("FaceWin_Form", "LoadHeadMesh", None))
        self.pushButton_13.setText(_translate("FaceWin_Form", "PushButton", None))
        self.faceRigBase_tabWidget.setTabText(self.faceRigBase_tabWidget.indexOf(self.tab_2), _translate("FaceWin_Form", "Riging", None))
        self.faceRigBase_tabWidget.setTabText(self.faceRigBase_tabWidget.indexOf(self.tab_3), _translate("FaceWin_Form", "页", None))
        self.faceRigBase_tabWidget.setTabText(self.faceRigBase_tabWidget.indexOf(self.tab_4), _translate("FaceWin_Form", "Blend_Corrective", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FaceWin_Form = QtGui.QWidget()
    ui = Ui_FaceWin_Form()
    ui.setupUi(FaceWin_Form)
    FaceWin_Form.show()
    sys.exit(app.exec_())

