# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceRig.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_faceUI_Form(object):
    def setupUi(self, faceUI_Form):
        faceUI_Form.setObjectName(_fromUtf8("faceUI_Form"))
        faceUI_Form.resize(470, 516)
        self.gridLayout = QtGui.QGridLayout(faceUI_Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(faceUI_Form)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 385, 308))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        self.toolBox.setFrameShape(QtGui.QFrame.Box)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 365, 132))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.importForeHeadBone_pushButton = QtGui.QPushButton(self.page_4)
        self.importForeHeadBone_pushButton.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.importForeHeadBone_pushButton.setObjectName(_fromUtf8("importForeHeadBone_pushButton"))
        self.gridLayout_6.addWidget(self.importForeHeadBone_pushButton, 0, 0, 1, 1)
        self.snapForeHeadMeshToHeadMesh_pushButton = QtGui.QPushButton(self.page_4)
        self.snapForeHeadMeshToHeadMesh_pushButton.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 113, 247);"))
        self.snapForeHeadMeshToHeadMesh_pushButton.setObjectName(_fromUtf8("snapForeHeadMeshToHeadMesh_pushButton"))
        self.gridLayout_6.addWidget(self.snapForeHeadMeshToHeadMesh_pushButton, 0, 1, 1, 1)
        self.rebulidForeHeadBone_pushButton = QtGui.QPushButton(self.page_4)
        self.rebulidForeHeadBone_pushButton.setStyleSheet(_fromUtf8("background-color: rgba(46, 76, 80, 220);"))
        self.rebulidForeHeadBone_pushButton.setObjectName(_fromUtf8("rebulidForeHeadBone_pushButton"))
        self.gridLayout_6.addWidget(self.rebulidForeHeadBone_pushButton, 2, 0, 1, 2)
        self.foreHeadBoneMir_pushButton = QtGui.QPushButton(self.page_4)
        self.foreHeadBoneMir_pushButton.setStyleSheet(_fromUtf8("background-color: rgb(46, 101, 113);"))
        self.foreHeadBoneMir_pushButton.setObjectName(_fromUtf8("foreHeadBoneMir_pushButton"))
        self.gridLayout_6.addWidget(self.foreHeadBoneMir_pushButton, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 377, 98))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 377, 98))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 377, 98))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_8 = QtGui.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 377, 98))
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.toolBox.addItem(self.page_8, _fromUtf8(""))
        self.page_9 = QtGui.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 377, 98))
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.toolBox.addItem(self.page_9, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.toolBox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadHeadMesh_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.loadHeadMesh_lineEdit.setObjectName(_fromUtf8("loadHeadMesh_lineEdit"))
        self.horizontalLayout_2.addWidget(self.loadHeadMesh_lineEdit)
        self.loadHeadMesh_pushButton = QtGui.QPushButton(self.groupBox)
        self.loadHeadMesh_pushButton.setObjectName(_fromUtf8("loadHeadMesh_pushButton"))
        self.horizontalLayout_2.addWidget(self.loadHeadMesh_pushButton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rebulidAllBone_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.rebulidAllBone_pushButton.setObjectName(_fromUtf8("rebulidAllBone_pushButton"))
        self.gridLayout_5.addWidget(self.rebulidAllBone_pushButton, 1, 0, 1, 1)
        self.bneMir_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.bneMir_pushButton.setObjectName(_fromUtf8("bneMir_pushButton"))
        self.gridLayout_5.addWidget(self.bneMir_pushButton, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.pushButton_2 = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 30, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tabWidgetPage2)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 460, 75, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName(_fromUtf8("tabWidgetPage3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tabWidgetPage3)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 30, 301, 371))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.tabWidget.addTab(self.tabWidgetPage3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.line = QtGui.QFrame(faceUI_Form)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(faceUI_Form)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(faceUI_Form)

    def retranslateUi(self, faceUI_Form):
        faceUI_Form.setWindowTitle(_translate("faceUI_Form", "faceUI_Win", None))
        self.groupBox.setTitle(_translate("faceUI_Form", "JntCreat", None))
        self.importForeHeadBone_pushButton.setText(_translate("faceUI_Form", "导入额头骨骼", None))
        self.snapForeHeadMeshToHeadMesh_pushButton.setText(_translate("faceUI_Form", "吸附模型", None))
        self.rebulidForeHeadBone_pushButton.setText(_translate("faceUI_Form", "重建额头骨骼", None))
        self.foreHeadBoneMir_pushButton.setText(_translate("faceUI_Form", "镜像", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("faceUI_Form", "ForeHead_Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("faceUI_Form", "Brow_Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("faceUI_Form", "Eye_Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("faceUI_Form", "Check_Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("faceUI_Form", "Nose_Create", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("faceUI_Form", "Mouth_Create", None))
        self.loadHeadMesh_pushButton.setText(_translate("faceUI_Form", "载入头部模型", None))
        self.groupBox_2.setTitle(_translate("faceUI_Form", "Jnt_Import", None))
        self.rebulidAllBone_pushButton.setText(_translate("faceUI_Form", "重置所有骨骼", None))
        self.bneMir_pushButton.setText(_translate("faceUI_Form", "镜像骨骼", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("faceUI_Form", "导入骨骼", None))
        self.pushButton_2.setText(_translate("faceUI_Form", "LoadMesh", None))
        self.pushButton_3.setText(_translate("faceUI_Form", "Rigging", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("faceUI_Form", "绑定", None))
        self.groupBox_3.setTitle(_translate("faceUI_Form", "BlendShape", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("faceUI_Form", "修形", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    faceUI_Form = QtGui.QWidget()
    ui = Ui_faceUI_Form()
    ui.setupUi(faceUI_Form)
    faceUI_Form.show()
    sys.exit(app.exec_())

